[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.9.0"

[[constraint]]
  version = "horizon-client-v0.0.1"
  name = "github.com/kinecosystem/go"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[prune]
  go-tests = true
  unused-packages = true
